### ISSUE TITLE
Satellite crashes after inputting API key

### ISSUE THREAD

**Issue by mikedamm** [felixbrucker/chia-dashboard-satellite#1]
**To Reproduce**
1. Download and unzip latest Linux build
2. execute binary
3. Input key from dashboard
4. Immediate crash

```root@xxx ~/chia-dashboard-satellite-1.1.1 # ./chia-dashboard-satellite
✔ Please enter the api key for this satellite … dbeb0881-xxxx-xxxx-xxxx-xxxxxxxxxxxx
events.js:315
    const result = ReflectApply(handler, this, args);
                   ^

TypeError: Cannot convert object to primitive value
    at WebSocket.<anonymous> (/snapshot/chia-dashboard-satellite/node_modules/chia-api/lib/connection.js)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/snapshot/chia-dashboard-satellite/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/snapshot/chia-dashboard-satellite/node_modules/ws/lib/receiver.js:437:14)
    at /snapshot/chia-dashboard-satellite/node_modules/ws/lib/receiver.js:394:23
    at /snapshot/chia-dashboard-satellite/node_modules/ws/lib/permessage-deflate.js:308:9
    at /snapshot/chia-dashboard-satellite/node_modules/ws/lib/permessage-deflate.js:391:7
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
```

Attempting to restart the process results in a crash with the same error.

**Comment by felixbrucker** [comment]
Which OS/distribution did you use?

**Comment by mikedamm** [comment]
`Ubuntu 20.04.2 LTS`
`Linux d1 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by felixbrucker** [comment]
Does the error still happen with the latest release of the satellite?

**Comment by mikedamm** [comment]
Looks like it is fixed now, thanks!
