### ISSUE TITLE
Repeated ERROR in debug.log

### ISSUE THREAD

**Issue by Underdoge** [felixbrucker/chia-dashboard-satellite#41]
**Describe the bug**
Whenever I start chia on macOS I start getting the following error repeatedly one after the other, in debug.log. Otherwise, chia seems to be working fine.

**To Reproduce**
1. launch chia on macOS Big Sur
2. Open log under /Users/<username>/.chia/debug.log

**Expected behavior**
I assume the ERROR should not happen

**Screenshots**
Thousands of repeated errors, here's the error text:
2021-05-14T13:43:19.654 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/*redacted*/chia-blockchain/chia-blockchain-gui/../chia/daemon/server.py", line 187, in safe_handle
    await socket.send(response)
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/Users/*redacted*/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**System (please complete the following information):**
 - OS: macOS Big Sur 11.3.1
 - NodeJs Version: 16.1.0
 - Chia version: 1.6.0

**Additional context**
Chia in general seems to be working fine. Maybe I can ignore this error? This was happening with previous versions of chia and npm, this didn't begin with the latest versions. I replaced the actual user with *redacted* in the error text above.

**Comment by felixbrucker** [comment]
When you terminate the satellite having a ws disconnect is normal. Nevertheless i'll look into actually properly closing the conenction before exiting 👍

**Comment by Underdoge** [comment]
Just realized this is the chia-dashboard-satellite github and not the actual chia repo. Sorry, closing.
